#!/usr/bin/env bash
# tests/scripts/refresh_known_failures.sh
#
# Regenerate tests/KNOWN_FAILURES.txt from current Bats failure set.
# Preserves existing comment suffixes (e.g. " # pre-existing WIP").
#
# Adapted from chisuhua/rdd-workflow/tests/scripts/refresh_known_failures.sh
# for rdd-workflow-e2e. Adds --reason flag for batch-adding new entries.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BASELINE="$REPO_ROOT/tests/KNOWN_FAILURES.txt"
TMP_DIR="$(mktemp -d -t rdd-e2e-refresh-XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Parse args
DEFAULT_REASON="reason required"
DRY_RUN=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --reason) DEFAULT_REASON="$2"; shift 2 ;;
        --dry-run)
            DRY_RUN=1
            export DRY_RUN
            shift ;;
        -h|--help)
            cat <<EOF
Usage: $0 [--reason <text>] [--dry-run]

Regenerate tests/KNOWN_FAILURES.txt from current Bats failures.

Options:
  --reason <text>  default comment for new entries (default: "reason required")
  --dry-run        print new baseline to stdout, don't write

Env vars:
  RDD_WORKFLOW_REPO   path to installed rdd-workflow
EOF
            exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if ! command -v bats >/dev/null 2>&1; then
    printf '❌ bats-core is required to refresh the baseline\n' >&2
    exit 127
fi

RDD_WORKFLOW_REPO="${RDD_WORKFLOW_REPO:-$HOME/.agents/skills/rdd-workflow}"
export RDD_WORKFLOW_REPO
if [[ ! -d "$RDD_WORKFLOW_REPO" ]]; then
    printf '❌ RDD_WORKFLOW_REPO not found: %s\n' "$RDD_WORKFLOW_REPO" >&2
    exit 1
fi

# Run bats
set +e
(cd "$REPO_ROOT" && bats tests/integration/ tests/_lib/) >"$TMP_DIR/bats-output" 2>&1
bats_status=$?
set -e

# Extract failure names
sed -nE 's/^not ok [0-9]+[[:space:]]+(.*)$/\1/p' "$TMP_DIR/bats-output" \
    | sed -E 's/[[:space:]]+#.*$//' \
    | sed '/^[[:space:]]*$/d' \
    | sort -u >"$TMP_DIR/actual"

if [[ "$bats_status" -eq 127 ]] && [[ ! -s "$TMP_DIR/actual" ]]; then
    printf '❌ Bats could not run; baseline was not changed\n' >&2
    tail -10 "$TMP_DIR/bats-output" >&2
    exit 127
fi

# Use Python heredoc (Oracle C1 safe — no bash $VAR interpolation into python)
BASELINE_PATH="$BASELINE" \
ACTUAL_PATH="$TMP_DIR/actual" \
DEFAULT_REASON="$DEFAULT_REASON" \
    python3 <<'PYEOF'
import os
from pathlib import Path

baseline = Path(os.environ["BASELINE_PATH"])
actual = Path(os.environ["ACTUAL_PATH"])
default_reason = os.environ["DEFAULT_REASON"]

comments = {}
if baseline.exists():
    for raw in baseline.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, comment = line.partition(" # ")
        comments[name.strip()] = comment.strip() if separator else ""

names = [line.strip() for line in actual.read_text(encoding="utf-8").splitlines() if line.strip()]
lines = []
for name in names:
    comment = comments.get(name, default_reason)
    lines.append(f"{name} # {comment}")

header = """# KNOWN_FAILURES.txt — baseline for rdd-workflow-e2e external test bed
#
# Format: <test_name> # <reason>
#
# Regenerated by: bash tests/scripts/refresh_known_failures.sh [--reason <text>]
# Lines in this file represent pre-existing, intentionally-accepted failures.
# report_regression.sh compares current bats output against this file:
#   - 新增失败 = failures here NOT in this file → exit 1 (must fix)
#   - 已知失败 = failures IN this file → acceptable (exit 0)
#
# After fixing a known failure, regenerate this file (it will be removed).
# When adding new failures, pass --reason "<why-acceptable>" so reviewers know.
"""

new_content = header
if lines:
    new_content += "\n".join(lines) + "\n"

if os.environ.get("DRY_RUN"):
    print(new_content)
else:
    baseline.parent.mkdir(parents=True, exist_ok=True)
    tmp = baseline.with_suffix(baseline.suffix + ".tmp")
    tmp.write_text(new_content, encoding="utf-8")
    tmp.replace(baseline)
    print(f"✅ refreshed {len(lines)} known failures: {baseline}")
PYEOF